name: Fit440
favicon: null
layout_spectrum: 0.7029260580893606
typography_spectrum: 0.7388610346242785
title: FIT440
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5836174481082708
  lightness: 0.5636588758789003
  saturation: 0.6692575383931398
  rhythmicContrast: 0.7413718965835869
purpose: []
