name: Fit440
favicon: null
layout_spectrum: 0.7029260580893606
typography_spectrum: 0.7388610346242785
title: FIT440
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82c3c5'
    - '#929396'
    - '#000000'
    - '#666666'
    - '#00ffff'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
